### PR TITLE
Issue 31 - Creating Landing Page

### PR DESCRIPTION
**Pull request by alanantony24**
@leicester70 here's the PR 😃

### CODE REVIEW

**Comment by alanantony24** [comment]
@leicester70 help merge plz, I dw merge myself and f up, there were merge conflicts which I fixed jn, but it looks a bit weird ah here checkout the ss

image

**Comment by alanantony24** [comment]
> @leicester70 help merge plz, I dw merge myself and f up, there were merge conflicts which I fixed jn, but it looks a bit weird ah here checkout the ss
> 
> image

also, since the login and signup are now tgt under the `TabbedElements`, what do we use the `LandingPage` for sia 🤣

**Comment by leicester70** [comment]
yeah sure no worries

**Comment by leicester70** [comment]
> > @leicester70 help merge plz, I dw merge myself and f up, there were merge conflicts which I fixed jn, but it looks a bit weird ah here checkout the ss
> > image
> 
> also, since the login and signup are now tgt under the `TabbedElements`, what do we use the `LandingPage` for sia 🤣

for noww i also not sure but if got your page and routing works i can just put ur stuff inside

**Comment by alanantony24** [comment]
okay can thanks thanks 😄

**Comment by leicester70** [comment]
> okay can thanks thanks 😄

is okay lah at least u got routing pages down

**Comment by leicester70** [comment]
> > okay can thanks thanks 😄
> 
> is okay lah at least u got routing pages down 👍🏻

image
do we need 'component' attribute if we use 'variant' do uk wats the difference? @alanantony24

**Pull request merged**
