### PR TITLE
Backend: Rate Limiter

### LINKED ISSUE #35: Implement Rate Limiter
see security tab

this fix important so that I don't get spammed into oblivion by some stranger on the internet and make mongoDB bill me billions

### PR DESCRIPTION
**Pull request by alanantony24**
Fixes #35

### CODE REVIEW

**Comment by alanantony24** [comment]
Yessss!!, Security checks also passed nice 😆

**Comment by alanantony24** [comment]
eh @leicester70 later can help me take a look at this PR and merge to main 😄 thanks

**Comment by leicester70** [comment]
> eh @leicester70 later can help me take a look at this PR and merge to main 😄 thanks

are u at india

**Comment by leicester70** [comment]
this feels so much more fun than office lol

**Comment by leicester70** [comment]
@alanantony24 

i saw the rate limiter thing, nice. didn't know express got a ratelimiter dependency, cool.

**Pull request merged**
